---
- name: Ensure Docker is installed
  # instala em todos as instancias
  hosts: all
  # usuario das instacias ec2
  remote_user: ec2-user
  # não pegar as informações da maquina, indica que vamos passar todas as informações necessárias do sistema
  gather_facts: false
  # inicia o modo super usuário nas máquinas
  become: true
  # ações a serem executadas
  tasks:
    - name: Install Docker
      yum: name=docker

    - name: Ensure docker service is started and enable
      service:
        name: docker
        state: started
        enabled: yes

- name: Initialize Swarm Mode
  # identificado no template hosts.tpl
  hosts: manager-leader
  remote_user: ec2-user
  gather_facts: false
  become: true
  tasks:
      # Registra se o docker swarm está ativo
    - shell: "docker info | grep 'Swarm' | awk -F'Swarm: ' '{print $NF}'"
      register: swarm_mode
    - name: Swarm init
      # inicializar o docker swarm no manager lider com ip privado
      command: docker swarm init --advertise-addr {{ private_ip }}
      # só executa o comando acima se o docker swarm estiver inativo
      when: swarm_mode.stdout == "inactive"